name: Create Pull Request
on:
  push:
    branches:
      - main

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update data
          committer: GitHub Actions <actions@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          title: 'Data Update'
          body: 'This is an automated pull request to update the data'
          labels: update,data
          assignees: user1,user2
          reviewers: reviewer1,reviewer2
          team-reviewers: team1,team2
          branch: example-branch-name
