name: Create Pull Request Workflow

on:
  push:
    branches:
      - main  # or the branch you want to trigger the workflow

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Make Changes
        run: |
          # Your script or commands to make changes
          echo "Example change" >> example-file.txt

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6.0.5
        with:
          token: "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"
          commit-message: "Automated change by GitHub Action"
          branch: "automated-changes-branch"
          title: "Automated changes"
          body: "This PR contains automated changes"
          labels: "automation,bot"
          assignees: "AkyrisPinange"
          reviewers: "AkyrisPinange,AkyrisPinange"
